### ISSUE TITLE
Can the system call pass 5 parameters?

### ISSUE THREAD

**Issue by nerososft** [MisaZhu/EwokOS#14]
Can the system call pass 5 parameters?

**Comment by nerososft** [comment]
I got the answer.

**Comment by MisaZhu** [comment]
How do you do it? Let me know .

**Comment by nerososft** [comment]
> How do you do it? Let me know .

https://github.com/SynestiaOS/SynestiaOS/blob/master/SourceCode/Kernel/src/interrupt.c

**Comment by nerososft** [comment]
> > How do you do it? Let me know .
> 
> in kernel
> https://github.com/SynestiaOS/SynestiaOS/blob/master/SourceCode/Kernel/src/interrupt.c
> line: 59
> 
> in libC
> https://github.com/SynestiaOS/SynestiaOS/blob/master/SourceCode/Libraries/LibC/include/sys.h
> line: 14


but I don't know why I can only use r1,r2, r4, r5, r6, r7

**Comment by MisaZhu** [comment]
Just checked out your implementation, It will work I guess, but it might cause some troubles  if you wanna port to some other platforms, coz there might not be many general regs like ARM. For your issue, some compilers  use general regs for some instructions, Usually developers can use  r0, r1, r2  safely, That's another reason why I only use r0, r1, r2 for syscall . If I need more arguments, I use proto_t to transfer more data.

**Comment by nerososft** [comment]
Thanks for answering, proto_t is indeed a good solution, I will try to use it later.
