### ISSUE TITLE
你的缺页异常怎么处理的鸭？ https://github.com/MisaZhu/EwokOS/blob/master/kernel/basic/kernel/irq.c

### ISSUE THREAD

**Issue by nerososft** [MisaZhu/EwokOS#16]
https://github.com/MisaZhu/EwokOS/blob/master/kernel/basic/kernel/irq.c

**Comment by MisaZhu** [comment]
There is not page fault handle yet, coz I don't have copy-on-write , it's on my todo list for sure .

**Comment by nerososft** [comment]
> There is not page fault handle yet, coz I don't have copy-on-write , it's on my todo list for sure .

got it
