### ISSUE TITLE
The latest code can't build pass

### ISSUE THREAD

**Issue by itmuse** [MisaZhu/EwokOS#17]
Error：
~/Documents/Git/EwokOS/system   master  make
cd basic;make
cd ./libs/libc;make
arm-none-eabi-gcc -Wstrict-prototypes -marm -pedantic -Wall -Wextra -msoft-float -fPIC -mapcs-frame -fno-builtin-printf -fno-builtin-memset -fno-builtin-snprintf -fno-builtin-sprintf -fno-builtin-fprintf -Wno-overlength-strings -fno-builtin-exit -fno-builtin-stdio -std=c99  -O2 -I ../../../build/include -Iinclude -Isys/include   -c -o sys/src/vfs.o sys/src/vfs.c
sys/src/vfs.c:386:5: error: conflicting types for 'vfs_create'
 int vfs_create(const char* fname, fsinfo_t* ret, int type, bool vfs_node_only) {
     ^
In file included from sys/src/vfs.c:1:0:
../../../build/include/sys/vfs.h:35:11: note: previous declaration of 'vfs_create' was here
 int       vfs_create(const char* fname, fsinfo_t* ret, int type);
           ^
make[2]: *** [sys/src/vfs.o] Error 1
make[1]: *** [basic_libs] Error 2
make: *** [basic_sys] Error 2

**Comment by MisaZhu** [comment]
try make clean first and try it again.

**Comment by itmuse** [comment]
> try make clean first and make again. or manually remove the system/build dir

It work, thanks.

**Comment by itmuse** [comment]
works
